name: PHP

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']
        laravel: ['6.*', '7.*', '8.*', '9.*', '10.*']
        exclude:
          - laravel: '6.*'
            php: '8.0'
          - laravel: '6.*'
            php: '8.1'
          - laravel: '6.*'
            php: '8.2'
          - laravel: '7.*'
            php: '8.0'
          - laravel: '7.*'
            php: '8.1'
          - laravel: '7.*'
            php: '8.2'
          - laravel: '8.*'
            php: '8.2'
          - laravel: '9.*'
            php: '7.4'
          - laravel: '10.*'
            php: '7.4'
          - laravel: '10.*'
            php: '8.0'
    name: PHP ${{ matrix.php }} on Laravel ${{ matrix.laravel }}
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, xdebug
        coverage: xdebug
    - name: Install dependencies
      run: |
        composer require --no-update --no-interaction "illuminate/notifications:${{ matrix.laravel }}"
        composer update --no-interaction --prefer-dist --no-suggest
    - name: Lint composer.json
      run: composer validate
    - name: Run Tests
      run: composer test:ci
